networks:
  dokploy-network:
    external: true
services:
  app:
    build: .
    environment:
      - PORT=4000
    expose:
      - '4000'
    networks:
      - dokploy-network
  # nginx:
  #   image: nginx:alpine
  #   depends_on:
  #     - app
  #   ports:
  #     - '80:60000'
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
